backend:
  name: github
  repo: ehsam211/ehlitestore
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Products"
    folder: "products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Product Name", name: "title", widget: "string"}
      - {label: "Base Price (USD)", name: "price", widget: "number"}
      - {label: "Image URL or Upload", name: "image", widget: "image"}
      - {label: "Category", name: "category", widget: "select", options: ["T-Shirts", "Hoodies", "Pants", "Accessories"]}
      - {label: "Sizes", name: "sizes", widget: "list", default: ["M", "L"]}
      - {label: "Description", name: "body", widget: "markdown"}
